# Generated by Django 3.1.3 on 2022-03-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='designation',
            new_name='role',
        ),
    ]
