# Generated by Django 4.0.2 on 2022-02-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
