# Generated by Django 4.0.2 on 2022-02-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Classroom_id',
            new_name='classroom_id',
        ),
    ]
