# Generated by Django 4.0.2 on 2022-02-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_rename_classroom_id_student_classroom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='percentage',
            field=models.IntegerField(),
        ),
    ]
